FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ingestion/ ./ingestion/
COPY processing/ ./processing/
COPY monitoring/ ./monitoring/
COPY validation/ ./validation/

CMD ["python", "ingestion/rss_ingestor.py"]
